version: '3'
services:
  sweat:
    container_name: sweat
    build:
      context: ./sweat_x/admin/
      dockerfile: Dockerfile
    image: sweat:1.0.0
    env_file:
      - ./app.env
    volumes:
      - /Users/chenweilong/sweat/home/webfile:/home/webfile
    ports:
      - "8880:8880"
    restart: always
